spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stocks?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update